using Microsoft.EntityFrameworkCore;

namespace NationalParkAPI.Models
{
    public class ParkAPIContext : DbContext
    {
        public ParkAPIContext(DbContextOptions<ParkAPIContext> options)
            : base(options)
            {
            }
            public DbSet<Park> Parks { get; set; }

            protected override void OnModelCreateing(ModelBuilder builder)
            {
                builder.Entity<Park>()
                    .HasData(
                        new Park { ParkId = 1, ParkName = "Acadia National Park", ParkLocation = "Maine", ParkDescription = " Acadia National Park is an American national park located in the state of Maine, southwest of Bar Harbor. The park preserves about half of Mount Desert Island, many adjacent smaller islands, and part of the Schoodic Peninsula on the coast of Maine. Acadia was initially designated Sieur de Monts National Monument by proclamation of President Woodrow Wilson in 1916. Sieur de Monts was renamed and redesignated Lafayette National Park by Congress in 1919—the first national park in the United States east of the Mississippi River and the only one in the Northeastern United States. The park was renamed Acadia National Park in 1929. More than 3.4 million people visited the park in 2019. ", ParkFauna = " Black Bear, Coyote, Fox, Raccoon, River Otters and many many more!! ", ParkFlora = "Balsam Fir, Eastern Hemlock, Red Pine, White spruce, Canada Mayflower, and lots more!! "}
                        new Park { ParkId = 2, ParkName = "Zion National Park", ParkLocation = "Utah", ParkDescription = " Zion National Park is an American national park located in southwestern Utah near the town of Springdale. A prominent feature of the 229-square-mile (590 km2) park is Zion Canyon, which is 15 miles (24 km) long and up to 2,640 ft (800 m) deep. The canyon walls are reddish and tan-colored Navajo Sandstone eroded by the North Fork of the Virgin River. The lowest point in the park is 3,666 ft (1,117 m) at Coalpits Wash and the highest peak is 8,726 ft (2,660 m) at Horse Ranch Mountain. Located at the junction of the Colorado Plateau, Great Basin, and Mojave Desert regions, the park has a unique geography and a variety of life zones that allow for unusual plant and animal diversity. Numerous plant species as well as 289 species of birds, 75 mammals (including 19 species of bat), and 32 reptiles inhabit the park's four life zones: desert, riparian, woodland, and coniferous forest. Zion National Park includes mountains, canyons, buttes, mesas, monoliths, rivers, slot canyons, and natural arches.", ParkFauna = " Carnivores: Black Bear, Coyote, Fox, Raccoon, River Otters and many many more!! ", ParkFlora = "Balsam Fir, Eastern Hemlock, Red Pine, White spruce, Canada Mayflower, and lots more!! "}
                        new Park { ParkId = 3, ParkName = "Acadia", ParkLocation = "Maine", ParkDescription = " Acadia National Park is an American national park located in the state of Maine, southwest of Bar Harbor. The park preserves about half of Mount Desert Island, many adjacent smaller islands, and part of the Schoodic Peninsula on the coast of Maine. Acadia was initially designated Sieur de Monts National Monument by proclamation of President Woodrow Wilson in 1916. Sieur de Monts was renamed and redesignated Lafayette National Park by Congress in 1919—the first national park in the United States east of the Mississippi River and the only one in the Northeastern United States. The park was renamed Acadia National Park in 1929. More than 3.4 million people visited the park in 2019. ", ParkFauna = " Carnivores: Black Bear, Coyote, Fox, Raccoon, River Otters and many many more!! ", ParkFlora = "Balsam Fir, Eastern Hemlock, Red Pine, White spruce, Canada Mayflower, and lots more!! "}
                        new Park { ParkId = 4, ParkName = "Acadia", ParkLocation = "Maine", ParkDescription = " Acadia National Park is an American national park located in the state of Maine, southwest of Bar Harbor. The park preserves about half of Mount Desert Island, many adjacent smaller islands, and part of the Schoodic Peninsula on the coast of Maine. Acadia was initially designated Sieur de Monts National Monument by proclamation of President Woodrow Wilson in 1916. Sieur de Monts was renamed and redesignated Lafayette National Park by Congress in 1919—the first national park in the United States east of the Mississippi River and the only one in the Northeastern United States. The park was renamed Acadia National Park in 1929. More than 3.4 million people visited the park in 2019. ", ParkFauna = " Carnivores: Black Bear, Coyote, Fox, Raccoon, River Otters and many many more!! ", ParkFlora = "Balsam Fir, Eastern Hemlock, Red Pine, White spruce, Canada Mayflower, and lots more!! "}
                        new Park { ParkId = 5, ParkName = "Acadia", ParkLocation = "Maine", ParkDescription = " Acadia National Park is an American national park located in the state of Maine, southwest of Bar Harbor. The park preserves about half of Mount Desert Island, many adjacent smaller islands, and part of the Schoodic Peninsula on the coast of Maine. Acadia was initially designated Sieur de Monts National Monument by proclamation of President Woodrow Wilson in 1916. Sieur de Monts was renamed and redesignated Lafayette National Park by Congress in 1919—the first national park in the United States east of the Mississippi River and the only one in the Northeastern United States. The park was renamed Acadia National Park in 1929. More than 3.4 million people visited the park in 2019. ", ParkFauna = " Carnivores: Black Bear, Coyote, Fox, Raccoon, River Otters and many many more!! ", ParkFlora = "Balsam Fir, Eastern Hemlock, Red Pine, White spruce, Canada Mayflower, and lots more!! "}
                        new Park { ParkId = 6, ParkName = "Acadia", ParkLocation = "Maine", ParkDescription = " Acadia National Park is an American national park located in the state of Maine, southwest of Bar Harbor. The park preserves about half of Mount Desert Island, many adjacent smaller islands, and part of the Schoodic Peninsula on the coast of Maine. Acadia was initially designated Sieur de Monts National Monument by proclamation of President Woodrow Wilson in 1916. Sieur de Monts was renamed and redesignated Lafayette National Park by Congress in 1919—the first national park in the United States east of the Mississippi River and the only one in the Northeastern United States. The park was renamed Acadia National Park in 1929. More than 3.4 million people visited the park in 2019. ", ParkFauna = " Carnivores: Black Bear, Coyote, Fox, Raccoon, River Otters and many many more!! ", ParkFlora = "Balsam Fir, Eastern Hemlock, Red Pine, White spruce, Canada Mayflower, and lots more!! "}
                        new Park { ParkId = 7, ParkName = "Acadia", ParkLocation = "Maine", ParkDescription = " Acadia National Park is an American national park located in the state of Maine, southwest of Bar Harbor. The park preserves about half of Mount Desert Island, many adjacent smaller islands, and part of the Schoodic Peninsula on the coast of Maine. Acadia was initially designated Sieur de Monts National Monument by proclamation of President Woodrow Wilson in 1916. Sieur de Monts was renamed and redesignated Lafayette National Park by Congress in 1919—the first national park in the United States east of the Mississippi River and the only one in the Northeastern United States. The park was renamed Acadia National Park in 1929. More than 3.4 million people visited the park in 2019. ", ParkFauna = " Carnivores: Black Bear, Coyote, Fox, Raccoon, River Otters and many many more!! ", ParkFlora = "Balsam Fir, Eastern Hemlock, Red Pine, White spruce, Canada Mayflower, and lots more!! "}
                        new Park { ParkId = 8, ParkName = "Acadia", ParkLocation = "Maine", ParkDescription = " Acadia National Park is an American national park located in the state of Maine, southwest of Bar Harbor. The park preserves about half of Mount Desert Island, many adjacent smaller islands, and part of the Schoodic Peninsula on the coast of Maine. Acadia was initially designated Sieur de Monts National Monument by proclamation of President Woodrow Wilson in 1916. Sieur de Monts was renamed and redesignated Lafayette National Park by Congress in 1919—the first national park in the United States east of the Mississippi River and the only one in the Northeastern United States. The park was renamed Acadia National Park in 1929. More than 3.4 million people visited the park in 2019. ", ParkFauna = " Carnivores: Black Bear, Coyote, Fox, Raccoon, River Otters and many many more!! ", ParkFlora = "Balsam Fir, Eastern Hemlock, Red Pine, White spruce, Canada Mayflower, and lots more!! "}
                        new Park { ParkId = 9, ParkName = "Acadia", ParkLocation = "Maine", ParkDescription = " Acadia National Park is an American national park located in the state of Maine, southwest of Bar Harbor. The park preserves about half of Mount Desert Island, many adjacent smaller islands, and part of the Schoodic Peninsula on the coast of Maine. Acadia was initially designated Sieur de Monts National Monument by proclamation of President Woodrow Wilson in 1916. Sieur de Monts was renamed and redesignated Lafayette National Park by Congress in 1919—the first national park in the United States east of the Mississippi River and the only one in the Northeastern United States. The park was renamed Acadia National Park in 1929. More than 3.4 million people visited the park in 2019. ", ParkFauna = " Carnivores: Black Bear, Coyote, Fox, Raccoon, River Otters and many many more!! ", ParkFlora = "Balsam Fir, Eastern Hemlock, Red Pine, White spruce, Canada Mayflower, and lots more!! "}
                        new Park { ParkId = 10, ParkName = "Acadia", ParkLocation = "Maine", ParkDescription = " Acadia National Park is an American national park located in the state of Maine, southwest of Bar Harbor. The park preserves about half of Mount Desert Island, many adjacent smaller islands, and part of the Schoodic Peninsula on the coast of Maine. Acadia was initially designated Sieur de Monts National Monument by proclamation of President Woodrow Wilson in 1916. Sieur de Monts was renamed and redesignated Lafayette National Park by Congress in 1919—the first national park in the United States east of the Mississippi River and the only one in the Northeastern United States. The park was renamed Acadia National Park in 1929. More than 3.4 million people visited the park in 2019. ", ParkFauna = " Carnivores: Black Bear, Coyote, Fox, Raccoon, River Otters and many many more!! ", ParkFlora = "Balsam Fir, Eastern Hemlock, Red Pine, White spruce, Canada Mayflower, and lots more!! "}

                    )
            }
    }
}